# Generated by Django 5.1.3 on 2025-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=20)),
                ('descrizione', models.TextField(max_length=100)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('posti_disponibili', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Corso',
                'verbose_name_plural': 'Corsi',
            },
        ),
    ]
