# Generated by Django 5.1.6 on 2025-04-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacterer',
            new_name='Manufacturer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufacterer',
            new_name='manufacturer',
        ),
    ]
